/**
 * Evolve Command — Self-Evolution (Owner Only)
 * Hands your instruction to Gemini, which reads and rewrites the bot's own
 * source files to carry it out, then restarts the bot to apply the change.
 * See utils/selfEvolve.js for the safety mechanics (checkpoint, syntax
 * check, rollback).
 */

const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const config = require('../../config');
const { runEvolve, ROOT } = require('../../utils/selfEvolve');
const github = require('../../utils/github');

function isEnabled() {
  return config.selfEvolve?.enabled === true || process.env.ALLOW_SELF_EVOLVE === 'true';
}

/**
 * After a local evolve run, also publish the changed files to GitHub as a
 * new branch + Pull Request — so the change survives a Railway redeploy
 * (which wipes local-only edits) and stays reviewable before it ever
 * reaches the default branch. Never pushes directly to main/master.
 * Silently skipped if GITHUB_TOKEN or config.github.owner/repo isn't set.
 */
async function publishToGitHub(instruction, changedFiles) {
  const owner = config.github?.owner;
  const repo = config.github?.repo;
  if (!github.hasToken() || !owner || !repo) return null;

  const base = config.github.defaultBranch || await github.getDefaultBranch(owner, repo);
  const branchName = `evolve-${Date.now()}`;
  await github.createBranch(owner, repo, branchName, base);

  for (const relPath of changedFiles) {
    const abs = path.join(ROOT, relPath);
    if (!fs.existsSync(abs)) continue; // file was removed locally; skip
    const content = fs.readFileSync(abs, 'utf8');
    let sha;
    try {
      const existing = await github.getFile(owner, repo, relPath, branchName);
      sha = existing.sha;
    } catch {
      // file doesn't exist on GitHub yet — creating new
    }
    await github.commitFile(owner, repo, relPath, content, `evolve: ${relPath}`, branchName, sha);
  }

  const prUrl = await github.createPullRequest(
    owner,
    repo,
    `Evolve: ${instruction.slice(0, 60)}`,
    branchName,
    base,
    `Auto-generated by \`.evolve\`.\n\n**Instruction:** ${instruction}\n\n**Changed files:**\n${changedFiles.map(f => `- ${f}`).join('\n')}\n\n⚠️ Review before merging.`
  );
  return prUrl;
}

function tryRestart() {
  return new Promise((resolve) => {
    exec('pm2 restart all', (error) => {
      if (!error) return resolve(true);
      setTimeout(() => process.exit(0), 500);
      resolve(false);
    });
  });
}

module.exports = {
  name: 'evolve',
  aliases: ['selfedit', 'selfevolve'],
  category: 'owner',
  description: 'Let the bot rewrite its own code to carry out an instruction (Owner Only)',
  usage: '.evolve <what to change>',
  ownerOnly: true,

  async execute(sock, msg, args, extra) {
    if (!isEnabled()) {
      return extra.reply(
        '❌ Self-evolve is disabled.\n\n' +
        'Enable it by setting `selfEvolve.enabled = true` in config.js ' +
        '(or the ALLOW_SELF_EVOLVE=true env var), then try again.\n\n' +
        'Only do this if the project is a git repo (for safe rollback) and ' +
        'you trust whoever has owner access to this bot.'
      );
    }

    const instruction = args.join(' ').trim();
    if (!instruction) {
      return extra.reply('❌ Usage: .evolve <describe what you want changed>\n\nExample: .evolve add a .coinflip command in commands/fun/');
    }

    try {
      await extra.reply('🧬 Evolving… reading the codebase and making the change. This can take a bit.');

      const result = await runEvolve(instruction);

      if (result.changedFiles.length === 0) {
        return extra.reply(`ℹ️ No files were changed.\n\n${result.summary}`);
      }

      const fileList = result.changedFiles.map(f => `• ${f}`).join('\n');

      let prNote = '';
      try {
        const prUrl = await publishToGitHub(instruction, result.changedFiles);
        if (prUrl) {
          prNote = `\n\n🔗 Pull Request opened for review (not merged automatically):\n${prUrl}`;
        }
      } catch (ghError) {
        console.error('[evolve] GitHub publish failed:', ghError.message);
        prNote = `\n\n⚠️ Local change applied, but publishing to GitHub failed: ${ghError.response?.data?.message || ghError.message}`;
      }

      await sock.sendMessage(msg.key.remoteJid, {
        text: `✅ Evolve complete (${result.steps} step(s)).\n\nChanged files:\n${fileList}\n\n${result.summary}${prNote}\n\n🔁 Restarting locally to apply the change…\nIf something looks wrong after restart, use .evolverollback.`
      }, { quoted: msg });

      await tryRestart();
    } catch (error) {
      console.error('Evolve error:', error);
      await extra.reply(`❌ Evolve failed: ${error.message}`);
    }
  }
};
